#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <unistd.h>
#include <errno.h>
#include <string.h>

int createRand(){
  int fd = open("/dev/urandom", O_RDONLY);
  if (fd < 0){
    printf("errno: %d error %s\n", errno, strerror(errno));
    printf("fd: %d\n", fd);
  }
  int buff[1];
  int rd = read(fd, buff, sizeof (buff));
  if (rd < 0){
    printf("errno: %d error %s\n", errno, strerror(errno));
    printf("rd: %d\n", rd);
  }
  close(fd);
  return buff[0];

  //check warnings after reading and writing as well
  //or int rand; read(fd, &rand, sizeof)
  //int has 4 bytes. you want to read 4 bytes
}


int main(){
  int randData[10];
  printf("\nGenerating random numbers:\n");
  for (int x = 0; x < 10; x++){
    randData[x] = createRand();
    printf("random %d: %d\n", x, randData[x]);
  }

  int fd = open("randFile", O_CREAT, 0644);
  if (fd < 0){
    printf("errno: %d error %s\n", errno, strerror(errno));
    printf("fd: %d\n", fd);
  }
  close(fd);

  printf("\nWriting numbers to file...\n");
  int wd = open("randFile", O_WRONLY);
  if (wd < 0){
    printf("errno: %d error %s\n", errno, strerror(errno));
    printf("wd: %d\n", wd);
  }
  write(wd, randData, sizeof (randData));
  close(wd);

  printf("\nReading numbers to file...\n");
  int myData[10];
  int rd = open("randFile", O_RDONLY);
  if (rd < 0){
    printf("errno: %d error %s\n", errno, strerror(errno));
    printf("rd: %d\n", rd);
  }
  read(rd, myData, sizeof (myData));
  close(rd);

  printf("\nVerification that written numbers were the same:\n");
  for (int x = 0; x < 10; x++){
    printf("random %d: %d\n", x, myData[x]);
  }

}


/*

A function that generates a random number by reading in the correct number of bytes from /dev/random.

A main function that:
1. Populates an array with 10 random numbers generated by your random function (print out each value)
     If your program seems to stall at this step, it's possible that your computer doesn't have enough entropy and is waiting, you can read from /dev/urandom instead.
2. Writes the array to a file
     Do not use a loop when writing to the file
3. Reads that file into a different array
     Do not use a loop when reading from the file
4. Prints out the contents of the second array to verify the random numbers are the same from step 1

Remember to use good practices, like checking return values for errors
Also remember to include a makefile that includes a separate run target 

*/
